encoding: utf-8
# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]
# Permalinks
# permalink:        pretty
permalink: /:basename/

# Setup
title:            The Third International Conference on AI-ML-Systems
tagline:          An Initiative of the COMSNETS Association
url:              https://www.aimlsystems.org
baseurl:          "/2023"

author:
  name:           'Abhijit Mondal'
  url:            https://abhijitmondal.in

# paginate:         5
paginate_path:    "blog/page:num/"
paginate: 2
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aimlsystems/


repository: aimlsystems/2023


collections:
  wpages:
    output: true
    permalink: /:path

shortname: "AIMLSystems'23"


cfp_pdf: AIMLSystems2023-CFP_v7.pdf
meitY_pdf: 
acm_latex: ACM_Latex_Template-0712.zip
schehule_pdf: 

